@api = http://localhost:44311/api


GET {{api}}/user/infoLog
Content-Type: application/json

###

POST {{api}}/user/login
Content-Type: application/json

{
    "user":"sthewar.rojano.escorcia@gmail.com",
    "pass":"Sthewar2021*"
}

###

POST {{api}}/user/login

###

Get {{api}}/service/getServiceAct

###

POST {{api}}/user/createUser
Content-Type: application/json

{
    "name":"sthewar1",
    "lastName":"rojano1",
    "typeId":1,
    "nit":"1002257366",
    "mail":"sthewar.rojano.escorcia@gmail.com",
    "pass":"",
    "numPhone":"3513",
    "userType":1
}

###
POST {{api}}/service/PostServices
Content-Type: application/json

{
    "nameService": "nameService",
    "Origen": "aqui",
    "Destino": "alla",
    "horaservicio": "12/12/12",
    "assistant": "sisas",
    "Inventory": 0,
    "pack": 0,
    "unpack": 0,
    "valor": "820.000",
    "idconductor": 1,
    "vigente": 1,
    "iduser": 1
  }

###
POST {{api}}/map/postMap
Content-Type: application/json

{
    "addressexit":"calle 131c #90-20",
    "addresarrival":"kr 152c #138d-43"
  }


###
GET {{api}}/pay/card